### ISSUE TITLE
Exception when server is queried before first rpki-client run

### ISSUE THREAD

**Issue by netixx** [ties/rpki-client-web#41]
Hello, 

I am getting the following error:
```
DEBUG:rpkiclientweb.__main__:Configuration: {'jitter': 600, 'verbosity': 2, 'cache_dir': PosixPath('/opt/rpkiclientweb/cache'), 'output_dir': PosixPath('/opt/rpkiclientweb/output'), 'interval': 900, 'timeout': 800, 'host': '0.0.0.0', 'port': 8888, 'rpki_client': PosixPath('/usr/sbin/rpki-client'), 'deadline': -1, 'rsync_command': None, 'additional_opts': [], 'trust_anchor_locators': [PosixPath('/etc/pki/tals/afrinic.tal'), PosixPath('/etc/pki/tals/apnic.tal'), PosixPath('/etc/pki/tals/lacnic.tal'), PosixPath('/etc/pki/tals/ripe.tal'), PosixPath('/etc/pki/tals/arin.tal')]}
DEBUG:asyncio:Using selector: EpollSelector
INFO:rpkiclientweb.web:starting webserver on 0.0.0.0:8888
INFO:rpkiclientweb.web:delaying by random delay of [0, 600] seconds of 452.462040 seconds
ERROR:aiohttp.server:Unhandled exception
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.10/pathlib.py", line 1095, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/rpkiclientweb/output/json'
ERROR:aiohttp.server:Unhandled exception
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/lib64/python3.10/site-packages/aiohttp/web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.10/pathlib.py", line 1095, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/rpkiclientweb/output/json'
```

Indeed, before the first run of rpki-client, the `json` file does not exist.
I am running the Docker version rpki-client-web.

At the moment I use `echo '{}' > /opt/rpkiclientweb/output/json && exec python3 -m rpkiclientweb -c /config/config.yml -v` as command, but this does not seem ideal.

**Comment by ties** [comment]
Thanks for the bug report. I will try to take a look at this over the weekend.

**Comment by ties** [comment]
Can you try the branch in #42? Specifically I am wondering if your client is OK with getting a non-http 200 response and realises that is an error.

**Comment by netixx** [comment]
I tested with `stayrtr` it didn't seem to like the empty json: 
```
stayrtr_1           | time="2021-11-22T15:09:45Z" level=debug msg="Refreshing cache from http://rpki-client-web:8888/objects/validated"
stayrtr_1           | time="2021-11-22T15:09:45Z" level=info msg="new cache file: Updating sha256 hash  -> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
stayrtr_1           | time="2021-11-22T15:09:45Z" level=error msg="Error updating: EOF"
stayrtr_1           | time="2021-11-22T15:09:45Z" level=debug msg="Refreshing slurm from /slurm.json"
stayrtr_1           | panic: runtime error: invalid memory address or nil pointer dereference
stayrtr_1           | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8064ab]
stayrtr_1           | 
stayrtr_1           | goroutine 1 [running]:
stayrtr_1           | main.(*state).updateFromNewState(0xc000234000)
stayrtr_1           |   /go/pkg/mod/github.com/bgp/stayrtr@v0.3.0/cmd/stayrtr/stayrtr.go:266 +0x1ab
stayrtr_1           | main.main()
stayrtr_1           |   /go/pkg/mod/github.com/bgp/stayrtr@v0.3.0/cmd/stayrtr/stayrtr.go:587 +0xaf5
```
(the stack amounts to an error accessing the "roas" attribute).

I think it would be better/more compatible to send an empty dict `{}` when no file is present on disk.
