### ISSUE TITLE
Catch and track error when parsing invalid JSON content

### ISSUE THREAD

**Issue by ties** [ties/rpki-client-web#91]
When parsing the JSON from a test environment that contains a large number of ASPA entries, the JSON parser aborts with the  error below.

The root cause is a syntax error in the JSON that is generated for this environment,
```
future: <Task finished name='Task-788' coro=<RpkiClient.update_validated_objects_gauge() done, defined at /opt/rpkiclientweb/rpkiclientweb/rpki_client.py:311> exception=JSONDecodeError('Expecting value: line 428561 column 63 (char 49269007)')>
Traceback (most recent call last):
  File "/opt/rpkiclientweb/rpkiclientweb/rpki_client.py", line 356, in update_validated_objects_gauge
    data = json.load(json_res)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 428561 column 63 (char 49269007)
```

**Comment by ties** [comment]
Root cause appears to be the JSON:
```
$ xzcat vrps.json.xz | jq '.'
parse error: Ex/pected another array element at line 428561, column 63
$ xzcat vrps.json.xz | head -n 428570 | tail -n 15

	],

	"provider_authorizations": {
		"ipv4": [
			{ "customer_asid": 28, "providers": [41881, 61036, 204096, ], "expires": 1682604454 },
			{ "customer_asid": 137, "providers": [208376, 211140, ], "expires": 1682590049 },
			{ "customer_asid": 378, "providers": [33924, 50616, ], "expires": 1682597251 },
			{ "customer_asid": 513, "providers": [], "expires": 1682604451 },
			{ "customer_asid": 553, "providers": [], "expires": 1682590052 },
			{ "customer_asid": 559, "providers": [], "expires": 1682584655 },
			{ "customer_asid": 680, "providers": [197303, 213032], "expires": 1682582260 },
			{ "customer_asid": 695, "providers": [], "expires": 1682584655 },
			{ "customer_asid": 696, "providers": [], "expires": 1682584655 },
			{ "customer_asid": 719, "providers": [60543], "expires": 1682583465 },

```

**Comment by ties** [comment]
(issue updated after I got questions on the root cause)

**Comment by ties** [comment]
Should be fixed after either https://github.com/openbsd/src/commit/38f920353dfa17dc7a6afe8e7018d4e7847f6d03 or https://github.com/openbsd/src/commit/157977775d3da1676dee68ee31698a081f6d1abd lands in a release.

**Comment by ties** [comment]
Confirming that 8.4 does output valid JSON when these ASPA objects are present. Will close this.
